name: Demo de Secretos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out el cÃ³digo
        uses: actions/checkout@v3

      - name: Usar un secreto
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}  # Acceso al secreto
        run: echo "El secreto es: $MY_SECRET"

      - name: Crear un archivo con el secreto
        run: echo "El secreto es: ${{ secrets.MY_SECRET }}" > secret.txt

      - name: Guardar el archivo de secreto como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: secret-file
          path: secret.txt


    
